# $schema: "https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json"
services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - COVERAGE_THRESHOLD=${COVERAGE_THRESHOLD:-80}