FROM python:3.11-alpine
WORKDIR /app
COPY . /app/
RUN apk add --no-cache gcc musl-dev python3-dev && \
    pip install --upgrade pip && \
    pip install cython && \
    pip install -r requirements.txt && \
    pip install pyyaml==6.0.1 && \
    chmod +x wait-for-mongodb.py
EXPOSE 8000
CMD ["sh", "-c", "python wait-for-mongodb.py && coverage run -m pytest && coverage report --fail-under=${COVERAGE_THRESHOLD:-80}"]
